### ISSUE TITLE
Name clash with Array

### ISSUE THREAD

**Issue by eriksvedang** [carpentry-org/hydrogen.carp#1]
When I load this I get an error: 

`error: typedef redefinition with different types ('struct Array' vs 'struct Array')`

Supposedly the other Array is in `hydrogenbuf.h`...

**Comment by hellerve** [comment]
Oh whoops! I added `#pragma once` to `core.h` because otherwise reloading `core.h` is not possible from any other C file included in Carp code, but forgot to contribute it back!

**Comment by eriksvedang** [comment]
Ah, that makes sense!

**Comment by eriksvedang** [comment]
Commenting out <core.h> in hydrogenbuf.h works for me.

**Comment by hellerve** [comment]
Removed `core.h` from `hydrogenbuf.h`.
